[package]
name = "sfd"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
yaml-rust = "0.4"
dialoguer = { version = "0.11.0" }
duct = "0.13.5"
structopt = "0.3.26"
